e2g_preds: /data/deyk/karthik/e2g_benchmarking/resources/test_ENCODE_E2G_DNase_only_K562.bed


# genescore_path: /data/deyk/karthik/e2g_benchmarking/resources/gene_scores.txt
# bed_dir: /data/deyk/karthik/e2g_benchmarking/results/bedfiles/
# tissue: 'K562' # can be a single value from the following: c("ALL", "BLD", "BRN", "K562", "GM12878", "Mono")



# rna: /data/deyk/scdata/DE48h_Huangfu_2023/rna_matrix.rds
# atac: /data/deyk/scdata/DE48h_Huangfu_2023/atac_matrix.rds
# meta: /data/deyk/scdata/DE48h_Huangfu_2023/metadata.rds
# # metacell_assignments: /data/deyk/karthik/DE_RNA_SEACells.csv
# celltype: 'DE'